# Generated by Django 6.0.4 on 2026-04-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('danger_level', models.CharField(choices=[('caution', '주의'), ('danger', '위험')], max_length=10, verbose_name='위험 상태')),
                ('action_status', models.CharField(choices=[('pending', '조치 필요'), ('in_progress', '조치 중'), ('completed', '조치 완료')], default='pending', max_length=20, verbose_name='조치 상태')),
                ('event_name', models.CharField(max_length=200, verbose_name='이벤트명')),
                ('source', models.CharField(max_length=100, verbose_name='발생원')),
                ('source_type', models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 전력'), ('worker', '작업자'), ('area', '위험구역')], max_length=10, verbose_name='발생원 유형')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('recommended_action', models.TextField(blank=True, verbose_name='권고 조치')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시간')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='조치 완료 시간')),
                ('related_workers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='연관 작업자')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL, verbose_name='조치자')),
            ],
            options={
                'verbose_name': '이벤트',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
