# Generated by Django 6.0.3 on 2026-04-16 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=20, unique=True, verbose_name='작업자ID')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험')], default='normal', max_length=10, verbose_name='현재 상태')),
                ('is_on_site', models.BooleanField(default=False, verbose_name='현장 출입 여부')),
                ('last_connected', models.DateTimeField(blank=True, null=True, verbose_name='마지막 연결 시간')),
                ('app_connected', models.BooleanField(default=False, verbose_name='앱 연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '작업자',
                'verbose_name_plural': '작업자 목록',
                'db_table': 'worker',
            },
        ),
    ]
