# Generated by Django 6.0.3 on 2026-04-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_version', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(help_text='slave01~slave16', max_length=10, verbose_name='채널')),
                ('current', models.FloatField(blank=True, help_text='통신불능=-1', null=True, verbose_name='전류(A)')),
                ('voltage', models.FloatField(blank=True, help_text='통신불능=-1', null=True, verbose_name='전압(V)')),
                ('power_usage', models.FloatField(blank=True, help_text='통신불능=-1', null=True, verbose_name='전력(W)')),
                ('relay_state', models.BooleanField(default=False, help_text='전원 ON=True / OFF=False', verbose_name='릴레이 상태')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='측정시간')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.smartpowerdevice')),
            ],
            options={
                'verbose_name': '전력 측정값',
                'verbose_name_plural': '전력 측정값 목록',
                'db_table': 'power_reading',
                'ordering': ['-measured_at'],
            },
        ),
    ]
