# Generated by Django 6.0.3 on 2026-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='장치ID')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='온도(°C)')),
                ('humi', models.FloatField(blank=True, null=True, verbose_name='습도(%)')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='측정시간')),
            ],
            options={
                'verbose_name': '환경 데이터',
                'verbose_name_plural': '환경 데이터 목록',
                'db_table': 'environment_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
