# Generated by Django 6.0.3 on 2026-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True, verbose_name='센서ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='장치명')),
                ('software_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='소프트웨어 버전')),
                ('location', models.CharField(max_length=100, verbose_name='위치')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험'), ('offline', '오프라인')], default='normal', max_length=10, verbose_name='상태')),
                ('is_connected', models.BooleanField(default=True, verbose_name='연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유해가스 센서',
                'verbose_name_plural': '유해가스 센서 목록',
                'db_table': 'gas_sensor',
            },
        ),
        migrations.CreateModel(
            name='SmartPowerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='설비ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='설비명')),
                ('software_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='소프트웨어 버전')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험'), ('offline', '오프라인')], default='normal', max_length=10, verbose_name='상태')),
                ('is_connected', models.BooleanField(default=True, verbose_name='연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '스마트 전력 설비',
                'verbose_name_plural': '스마트 전력 설비 목록',
                'db_table': 'smart_power_device',
            },
        ),
    ]
