# Generated by Django 6.0.4 on 2026-04-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=20, unique=True, verbose_name='센서ID')),
                ('location', models.CharField(max_length=100, verbose_name='위치')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험'), ('offline', '오프라인')], default='normal', max_length=10, verbose_name='상태')),
                ('is_connected', models.BooleanField(default=True, verbose_name='연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유해가스 센서',
            },
        ),
        migrations.CreateModel(
            name='SmartPowerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='설비ID')),
                ('name', models.CharField(max_length=100, verbose_name='설비명')),
                ('load_rate', models.FloatField(default=0, verbose_name='부하율(%)')),
                ('temperature', models.FloatField(default=0, verbose_name='온도(℃)')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험'), ('offline', '오프라인')], default='normal', max_length=10, verbose_name='상태')),
                ('is_connected', models.BooleanField(default=True, verbose_name='연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
            ],
            options={
                'verbose_name': '스마트 전력 설비',
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(choices=[('O2', '산소'), ('CO', '일산화탄소'), ('CO2', '이산화탄소'), ('H2S', '황화수소'), ('H2', '수소'), ('CH4', '메탄'), ('C3H8', '프로판'), ('C4H10', '부탄')], max_length=10, verbose_name='가스 종류')),
                ('value', models.FloatField(verbose_name='농도')),
                ('unit', models.CharField(default='%', max_length=10, verbose_name='단위')),
                ('danger_level', models.CharField(default='normal', max_length=10, verbose_name='위험도')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.gassensor')),
            ],
            options={
                'verbose_name': '가스 측정값',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=20, unique=True, verbose_name='작업자ID')),
                ('status', models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험')], default='normal', max_length=10, verbose_name='현재 상태')),
                ('is_on_site', models.BooleanField(default=False, verbose_name='현장 출입 여부')),
                ('last_connected', models.DateTimeField(blank=True, null=True, verbose_name='마지막 연결 시간')),
                ('app_connected', models.BooleanField(default=False, verbose_name='앱 연결 상태')),
                ('x_position', models.FloatField(default=0, verbose_name='X 좌표')),
                ('y_position', models.FloatField(default=0, verbose_name='Y 좌표')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '작업자',
            },
        ),
    ]
