# Generated by Django 6.0.4 on 2026-04-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work_area', '작업 구역 안전 확인'), ('piping', '배관 작업 안전 확인'), ('welding', '용접 및 화기 작업 확인'), ('high_work', '고소 작업 확인'), ('equipment', '설비 및 장비 확인'), ('gas_env', '가스 및 환경 위험 확인'), ('workers', '주변 작업자 안전 확인'), ('emergency', '비상 대응 확인'), ('final', '최종 확인')], max_length=20, verbose_name='카테고리')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('content', models.TextField(verbose_name='항목 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '체크리스트 항목',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='점검 날짜')),
                ('checklist_completed', models.BooleanField(default=False, verbose_name='체크리스트 완료')),
                ('vr_completed', models.BooleanField(default=False, verbose_name='VR 교육 완료')),
                ('ppe_confirmed', models.BooleanField(default=False, verbose_name='PPE 착용 확인')),
                ('vr_progress_seconds', models.IntegerField(default=0, verbose_name='VR 진행 시간(초)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '안전 확인 이력',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='체크 여부')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety.checklistitem')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='safety.safetychecklist')),
            ],
            options={
                'unique_together': {('checklist', 'item')},
            },
        ),
    ]
