# Generated by Django 6.0.3 on 2026-04-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_version', models.CharField(blank=True, max_length=20, null=True)),
                ('co', models.FloatField(blank=True, null=True, verbose_name='일산화탄소(ppm)')),
                ('h2s', models.FloatField(blank=True, null=True, verbose_name='황화수소(ppm)')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='이산화탄소(ppm)')),
                ('o2', models.FloatField(blank=True, null=True, verbose_name='산소(%)')),
                ('no2', models.FloatField(blank=True, null=True, verbose_name='이산화질소(ppm)')),
                ('so2', models.FloatField(blank=True, null=True, verbose_name='이산화황(ppm)')),
                ('o3', models.FloatField(blank=True, null=True, verbose_name='오존(ppm)')),
                ('nh3', models.FloatField(blank=True, null=True, verbose_name='암모니아(ppm)')),
                ('voc', models.FloatField(blank=True, null=True, verbose_name='휘발성유기화합물(ppm)')),
                ('danger_level', models.CharField(choices=[('위험', '위험'), ('주의', '주의'), ('정상', '정상')], default='정상', max_length=5, verbose_name='위험도')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='측정시간')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.gassensor')),
            ],
            options={
                'verbose_name': '가스 측정값',
                'verbose_name_plural': '가스 측정값 목록',
                'db_table': 'gas_reading',
                'ordering': ['-measured_at'],
            },
        ),
    ]
